AllCops:
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'features/**/*'
    - 'spec/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*' # For CI broken
    - 'tmp/**/*'
    - '.git/**/*'

# pending status for avoiding the warning

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - config/**/*
    - spec/**/*

Style/RedundantParentheses:
  Enabled: false

# I can correct It by -a
Style/FrozenStringLiteralComment:
  Safe: true
  Enabled: false

# About ABC http://wiki.c2.com/?AbcMetric
Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 100

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
