country = Country.find_by_name('Mexico')
# States of Mexico
State.create(name: 'Aguascalientes', country_id: country.id, code: 'AGU')
State.create(name: 'Baja California', country_id: country.id, code: 'BCN')
State.create(name: 'Baja California Sur', country_id: country.id, code: 'BCS')
State.create(name: 'Campeche', country_id: country.id, code: 'CAM')
State.create(name: 'Chiapas', country_id: country.id, code: 'CHP')
State.create(name: 'Chihuahua', country_id: country.id, code: 'CHH')
State.create(name: 'Ciudad de México', country_id: country.id, code: 'CMX')
State.create(name: 'Coahuila', country_id: country.id, code: 'COA')
State.create(name: 'Colima', country_id: country.id, code: 'COL')
State.create(name: 'Durango', country_id: country.id, code: 'DUR')
State.create(name: 'Guanajuato', country_id: country.id, code: 'GUA')
State.create(name: 'Guerrero', country_id: country.id, code: 'GRO')
State.create(name: 'Hidalgo', country_id: country.id, code: 'HID')
State.create(name: 'Jalisco', country_id: country.id, code: 'HID')
State.create(name: 'México', country_id: country.id, code: 'MEX')
State.create(name: 'Michoacán', country_id: country.id, code: 'MIC')
State.create(name: 'Morelos', country_id: country.id, code: 'MOR')
State.create(name: 'Nayarit', country_id: country.id, code: 'NAY')
State.create(name: 'Nuevo León', country_id: country.id, code: 'NLE')
State.create(name: 'Oaxaca', country_id: country.id, code: 'OAX')
State.create(name: 'Puebla', country_id: country.id, code: 'PUE')
State.create(name: 'Querétaro', country_id: country.id, code: 'QUE')
State.create(name: 'Quintana Roo', country_id: country.id, code: 'ROO')
State.create(name: 'San Luis Potosí', country_id: country.id, code: 'SLP')
State.create(name: 'Sinaloa', country_id: country.id, code: 'SIN')
State.create(name: 'Sonora', country_id: country.id, code: 'SON')
State.create(name: 'Tamaulipas', country_id: country.id, code: 'TAM')
State.create(name: 'Tabasco', country_id: country.id, code: 'TAB')
State.create(name: 'Tlaxcala', country_id: country.id, code: 'TLA')
State.create(name: 'Veracruz', country_id: country.id, code: 'VER')
State.create(name: 'Yucatán', country_id: country.id, code: 'YUC')
State.create(name: 'Zacatecas', country_id: country.id, code: 'ZAC')