default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV.fetch("POSTGRES_HOST", 'localhost') %>
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: school_administration_development

test:
  <<: *default
  user: <%= ENV.fetch("PGUSER") %>
  password: <%= ENV.fetch("PGPASSWORD") %>
  database: school_administration_test

production:
  <<: *default
  database: school_administration_production

staging:
  <<: *default
  database: school_administration_staging
